### ISSUE TITLE
个人理财亏钱/赚钱如何记账

### ISSUE THREAD

**Issue by shuaichi** [getmoneynote/moneynote-api#2]
账本中有资产账本，help中有很多记账案例，但没有针对理财亏钱赚钱的记账案例。
如果直接调整余额，则不能体现理财的盈亏。

**Comment by DanielHCheung** [comment]
一般是记录成本价、净值、数值实时估算，需要同时接入交易所数据，这个不知道后面会不会做。理财部分单独用同花顺账本吧

**Comment by imichaelwong** [comment]
收入里面建一个理财收入，支出里面建一个理财亏损，按你自己周期结算一次就可以了

**Comment by kevin8080** [comment]
理财确实不直观，我想记录盈亏的，根本看不出来
