### ISSUE TITLE
哥  你的代码不全  我这里少了QGroup的类  你要不开个分支  稳定版本传一份咋样

### ISSUE THREAD

**Issue by YaOdna-zxx** [getmoneynote/moneynote-api#23]

**Comment by markliu2013** [comment]
大哥，没少，你要玩代码，就得会java啊。QGroup是querydsl框架生成的，类似lombok生成getter setter方法

**Comment by YaOdna-zxx** [comment]
> querydsl

querydsl没用过  我还以为少类呢   这个我需要像lombok一样加一个插件吗

**Comment by YaOdna-zxx** [comment]
> 大哥，没少，你要玩代码，就得会java啊。QGroup是querydsl框架生成的，类似lombok生成getter setter方法
嗷嗷 我没用过querydsl框架  我还以为少类呢  这个也像lombok一样装一个插件吗

**Comment by YaOdna-zxx** [comment]
> > 大哥，没少，你要玩代码，就得会java啊。QGroup是querydsl框架生成的，类似lombok生成getter setter方法
> > 嗷嗷 我没用过querydsl框架  我还以为少类呢  这个也像lombok一样装一个插件吗
启动开发之类的我这边是没有问题了哈  谢谢大哥
