### ISSUE TITLE
能做一个内外网区别的功能吗

### ISSUE THREAD

**Issue by ZhiqiKou** [getmoneynote/moneynote-api#4]
想把项目部署到群晖docker上，然后能新增一个功能就是说app能设置两个后端地址，一个是公网地址，一个是内网地址，当连接到某个路由器后，使用内网地址，反之使用公网地址？

**Comment by lengcangkuganmian** [comment]
其实你可以在路由器上实现这个效果，路由器做个劫持，把这个域名解析到内网地址就行了

**Comment by lowlandsheperd** [comment]
这个问题不应该在APP层面解决，应该是DNS层面的问题

并且这个项目流量很小，即使在内网用公网转一道也问题不大吧
