### ISSUE TITLE
能否增加上传截图功能

### ISSUE THREAD

**Issue by zlhdd108** [getmoneynote/moneynote-api#7]
类似“挖财记账”里面，每一笔可以上传截图，这样比较方便

**Comment by markliu2013** [comment]
图片不好存储啊

**Comment by zlhdd108** [comment]
选一个路径吧，docker就mount就行了；作为一个可选功能，数据库关联图片，不过可能上传的图片要改名，按照日期或者记账的主键来命名？这样行不？

**Comment by kyuuketsu** [comment]
> 

能不能调用docker上面的自建图床接口，然后就图片上传到图床

**Comment by markliu2013** [comment]
已支持。
